#test
from openai import OpenAI
import json
import logging

logger = logging.getLogger(__name__)
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(name)s | %(levelname)s | %(message)s",
    force=True  # Overrides any prior logging configurations
)
logger.info("Process started")

client = OpenAI()
logger.info("OpenAI client initialized")

# 1. Define a list of callable tools for the model
tools = [
    {
        "type": "function",
        "name": "get_horoscope",
        "description": "Get today's horoscope for an astrological sign.",
        "parameters": {
            "type": "object",
            "properties": {
                "sign": {
                    "type": "string",
                    "description": "An astrological sign like Taurus or Aquarius",
                },
            },
            "required": ["sign"],
        },
    },
]

def get_horoscope(sign):
    return f"{sign}: Next Tuesday you will befriend a baby otter."

# Create a running input list we will add to over time
input_list = [
    {"role": "user", "content": "What is my horoscope? I am an Aquarius."}
]

# 2. Prompt the model with tools defined
response = client.responses.create(
    model="gpt-5",
    tools=tools,
    input=input_list,
)

logging.info("First model response:")
logging.info(response.model_dump_json(indent=2))

#print("First model response:")
#print(response.model_dump_json(indent=2))

# Save function call outputs for subsequent requests
input_list += response.output
print("Input list after first response:")
print(input_list)


for item in response.output:
    if item.type == "function_call":
        if item.name == "get_horoscope":
            # 3. Execute the function logic for get_horoscope
            sign = json.loads(item.arguments)["sign"]
            horoscope = get_horoscope(sign)
            
            # 4. Provide function call results to the model
            input_list.append({
                "type": "function_call_output",
                "call_id": item.call_id,
                "output": horoscope,
            })

logging.info("Input list after processing function calls:")
logger.info(input_list)

#print("Final input:")
#print(input_list)

response = client.responses.create(
    model="gpt-5",
    instructions="Respond only with a horoscope generated by a tool.",
    tools=tools,
    input=input_list,
)

logging.info("Final model response:")
logger.info(response.model_dump_json(indent=2))
logger.info("Final output text:")
logger.info(response.output_text)

# 5. The model should be able to give a response!
#print("Final output:")
#print(response.model_dump_json(indent=2))
#print("\n" + response.output_text)