from openai import OpenAI
import json
import logging
from pydantic import BaseModel,Field

logger = logging.getLogger(__name__)
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(name)s | %(levelname)s | %(message)s",
    force=True  # Overrides any prior logging configurations
)
logger.info("Process started")

client = OpenAI()
logger.info("OpenAI client initialized")

# 1. Define the actual function which will return the response
def get_weather(location, units="c"):
    """This is the local python code that fetches real data."""
    # Replace this with a real API call to a weather service if needed
    return json.dumps({"location": location, "temperature": "22", "units": "celsius"})

# 2. Define a list of callable tools for the model
tools = [
    {
        "type": "function",
        "name": "get_weather",
        "description": "Retrieves current weather for the given location.",
        "parameters": {
            "type": "object",
            "properties": {
            "location": {
                "type": "string",
                "description": "City and country e.g. Bogotá, Colombia"
            },
            "units": {
                "type": "string",
                "enum": ["celsius", "fahrenheit"],
                "description": "Units the temperature will be returned in."
            }
            },
            "required": ["location", "units"],
            "additionalProperties": False
        },
        "strict": True
    },
]

# 3. Streaming function call 
stream = client.responses.create(
    model="gpt-4.1",
    input=[{"role": "user", "content": "What's the weather like in Paris today?"}],
    tools=tools,
    stream=True
)

print("stream output")
print(stream)

input_list = []

for event in stream:
    #print(event.type)
    # 1. Skip metadata events like ResponseCreatedEvent safely
    if event.type == "response.created":
        previous_response_id = event.response.id
        continue 

    # 2. Extract streaming text as it generates
    elif event.type == "response.text.delta":
        print(event.delta, end="", flush=True)

    # 3. Detect when the model requests a function call 
    elif event.type == "response.output_item.done":
        print(event.item)
        item = event.item
        
        if item.type == "function_call":
            input_list.append(item)    

print("Updated input_list")
print(input_list)


def call_function(name, args):
    if name == "get_weather":
        return get_weather(**args)

print("previous_response_id " + previous_response_id)

# After the stream ends, execute any requested weather lookups
for tool_call in input_list:
    if tool_call.name == "get_weather":
        name = tool_call.name
        args = json.loads(tool_call.arguments)
        result = call_function(name, args)
        print(f"\nExecuting get_weather for {args['location']}...")
        
        input_list.append({
            "type": "function_call_output",
            "call_id": tool_call.call_id,
            "output": str(result)
        }) 
        
# 4. Define the desired output structure
class WeatherResponse(BaseModel):
    location: str = Field(description="The city and state/country being queried")
    temperature: float = Field(description="The current temperature in Celsius")
    condition: str = Field(description="The general weather condition")

response2 = client.responses.parse(
    model="gpt-5",
    instructions="Respond only with a weather generated by a tool.",
    tools=tools,
    input=input_list,
    text_format=WeatherResponse,
)

# 5. The model should be able to give a response!
print("Final output:")
print(response2.model_dump_json(indent=2))
print("\n" + response2.output_text)
