from openai import OpenAI
import json
import logging
from pydantic import BaseModel,Field

logger = logging.getLogger(__name__)
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(name)s | %(levelname)s | %(message)s",
    force=True  # Overrides any prior logging configurations
)
logger.info("Process started")

client = OpenAI()
logger.info("OpenAI client initialized")

# 1. Define the actual function which will return the response
def get_weather(location, units="c"):
    """This is the local python code that fetches real data."""
    # Replace this with a real API call to a weather service if needed
    return json.dumps({"location": location, "temperature": "22", "units": "celsius"})

# 1. Define a list of callable tools for the model
tools = [
    {
        "type": "function",
        "name": "get_weather",
        "description": "Retrieves current weather for the given location.",
        "parameters": {
            "type": "object",
            "properties": {
            "location": {
                "type": "string",
                "description": "City and country e.g. Bogotá, Colombia"
            },
            "units": {
                "type": "string",
                "enum": ["celsius", "fahrenheit"],
                "description": "Units the temperature will be returned in."
            }
            },
            "required": ["location", "units"],
            "additionalProperties": False
        },
        "strict": True
    },
]

# Prompt to be passed for the first time
input_list = [
    {"role": "user", "content": "What is the weather of Paris today?"}
]

# 2. Prompt the model with tools defined
response = client.responses.create(
    model="gpt-5",
    tools=tools,
    input=input_list,
)

logging.info("First model response:")
logging.info(response.model_dump_json(indent=2))

# Save function call outputs for subsequent requests
input_list += response.output
print("Input list after first response:")
print(input_list)

def call_function(name, args):
    if name == "get_weather":
        return get_weather(**args)

for tool_call in response.output:
    if tool_call.type != "function_call":
        continue

    name = tool_call.name
    args = json.loads(tool_call.arguments)
    print(name)
    print(args)

    result = call_function(name, args)
    input_list.append({
        "type": "function_call_output",
        "call_id": tool_call.call_id,
        "output": str(result)
    })
    
logging.info("Input list after processing function calls:")
logger.info(input_list)

# efine the desired output structure
class WeatherResponse(BaseModel):
    location: str = Field(description="The city and state/country being queried")
    temperature: float = Field(description="The current temperature in Celsius")
    condition: str = Field(description="The general weather condition")

response2 = client.responses.parse(
    model="gpt-5",
    instructions="Respond only with a weather generated by a tool.",
    tools=tools,
    input=input_list,
    text_format=WeatherResponse,
)

logging.info("Final model response:")
logger.info(response2.model_dump_json(indent=2))
logger.info("Final output text:")
logger.info(response2.output_text)

# 5. The model should be able to give a response!
#print("Final output:")
#print(response.model_dump_json(indent=2))
#print("\n" + response.output_text)